// Reads ../Farm OS/tokens.js, parses each oklch(L C H) color via culori,
// converts to sRGB hex, and emits ../src/theme/tokens.ts as a typed module.
// Run with: npm run tokens:gen

import { formatHex, oklch } from 'culori';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SRC = resolve(ROOT, '..', 'Farm OS', 'tokens.js');
const OUT = resolve(ROOT, 'src', 'theme', 'tokens.ts');
const OUT_TAILWIND = resolve(ROOT, 'src', 'theme', 'tokens.tailwind.cjs');

type ThemeName = 'light' | 'dark' | 'outdoor';

const src = readFileSync(SRC, 'utf8');

function extractObjectBlock(name: ThemeName): string {
  // Matches: const <name> = { ... };
  const re = new RegExp(`const ${name}\\s*=\\s*\\{`);
  const m = src.match(re);
  if (!m) throw new Error(`could not find ${name} block`);
  const start = m.index! + m[0].length - 1; // points at '{'
  let depth = 0;
  for (let i = start; i < src.length; i++) {
    const ch = src[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) return src.slice(start, i + 1);
    }
  }
  throw new Error(`unterminated ${name} block`);
}

function parseEntries(block: string): Array<[string, string]> {
  // Strip block comments and line comments inside the object
  const cleaned = block.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/.*$/gm, '');
  const out: Array<[string, string]> = [];
  // Match: key: 'value' or key: "value"
  const re = /(\w+)\s*:\s*(?:'([^']*)'|"([^"]*)")\s*,?/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(cleaned)) !== null) {
    out.push([m[1]!, (m[2] ?? m[3]) as string]);
  }
  return out;
}

function oklchToHex(value: string): string {
  // Examples: 'oklch(0.985 0.004 90)', 'oklch(1 0 0)', 'oklch(0.55 0.16 240)'
  const m = value.match(/oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*\)/);
  if (!m) return value;
  const [, lStr, cStr, hStr] = m;
  const L = parseFloat(lStr!);
  const C = parseFloat(cStr!);
  const H = parseFloat(hStr!);
  const color = oklch({ mode: 'oklch', l: L, c: C, h: H });
  return formatHex(color) ?? value;
}

const themes: Record<ThemeName, Record<string, string>> = {
  light: {},
  dark: {},
  outdoor: {},
};

(['light', 'dark', 'outdoor'] as ThemeName[]).forEach((name) => {
  const block = extractObjectBlock(name);
  for (const [k, v] of parseEntries(block)) {
    themes[name][k] = v.startsWith('oklch(') ? oklchToHex(v) : v;
  }
});

// Verify both themes have the same keys
const refKeys = Object.keys(themes.light).sort();
for (const m of ['dark', 'outdoor'] as const) {
  const keys = Object.keys(themes[m]).sort();
  const missing = refKeys.filter((k) => !keys.includes(k));
  const extra = keys.filter((k) => !refKeys.includes(k));
  if (missing.length || extra.length) {
    console.warn(`[${m}] missing=${missing.join(',')} extra=${extra.join(',')}`);
  }
}

const header = `// AUTO-GENERATED by scripts/oklch-to-hex.ts from "Farm OS/tokens.js".
// Do not edit by hand. Regenerate with: npm run tokens:gen
// Source uses oklch(L C H); converted to sRGB hex via culori for native rendering.
`;

const radii = `export const radii = { xs: 6, sm: 10, md: 14, lg: 18, xl: 24, pill: 9999 } as const;`;
const space = `export const space = { 0:0, 1:4, 2:8, 3:12, 4:16, 5:20, 6:24, 7:32, 8:40, 9:48, 10:64 } as const;`;
const type = `export const type = {
  family: 'IBMPlexSansThai_400Regular',
  familyMedium: 'IBMPlexSansThai_500Medium',
  familySemi: 'IBMPlexSansThai_600SemiBold',
  familyBold: 'IBMPlexSansThai_700Bold',
  familyNum: 'IBMPlexSans_400Regular',
  familyNumMedium: 'IBMPlexSans_500Medium',
  familyNumSemi: 'IBMPlexSans_600SemiBold',
  familyNumBold: 'IBMPlexSans_700Bold',
  sizes: { xs: 11, sm: 13, base: 15, md: 16, lg: 18, xl: 22, xxl: 28, hero: 34 },
  weights: { reg: '400', med: '500', semi: '600', bold: '700' },
} as const;`;

function objToTs(obj: Record<string, string>): string {
  const entries = Object.entries(obj)
    .map(([k, v]) => `  ${k}: '${v.replace(/'/g, "\\'")}',`)
    .join('\n');
  return `{\n${entries}\n}`;
}

const palette = `export type ThemeMode = 'light' | 'dark' | 'outdoor';

export type ThemePalette = {
${refKeys.map((k) => `  ${k}: string;`).join('\n')}
};

export const themes: Record<ThemeMode, ThemePalette> = {
  light: ${objToTs(themes.light)},
  dark: ${objToTs(themes.dark)},
  outdoor: ${objToTs(themes.outdoor)},
};
`;

const out = [header, '', radii, '', space, '', type, '', palette].join('\n');

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out, 'utf8');
console.log(`wrote ${OUT}`);

// Sibling CommonJS file consumed by tailwind.config.js (Node can't import .ts).
const radiiObj = { xs: 6, sm: 10, md: 14, lg: 18, xl: 24, pill: 9999 };
const typeObj = {
  family: 'IBMPlexSansThai_400Regular',
  familyMedium: 'IBMPlexSansThai_500Medium',
  familySemi: 'IBMPlexSansThai_600SemiBold',
  familyBold: 'IBMPlexSansThai_700Bold',
  familyNum: 'IBMPlexSans_400Regular',
  familyNumMedium: 'IBMPlexSans_500Medium',
  familyNumSemi: 'IBMPlexSans_600SemiBold',
  familyNumBold: 'IBMPlexSans_700Bold',
};
const cjs = `// AUTO-GENERATED. Used by tailwind.config.js.
module.exports = ${JSON.stringify({ themes, radii: radiiObj, type: typeObj }, null, 2)};
`;
writeFileSync(OUT_TAILWIND, cjs, 'utf8');
console.log(`wrote ${OUT_TAILWIND}`);
